# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b50743cbfddc02ce2606f537b9235d8f736cc4cb61c061f3a950352e8560de24bee2fb25cc608156e887aa5e8bd662352a7218d9a89297c8899d466816c8ec6

test:
  secret_key_base: f715b606165a29af35525b82a3406ebf3fcc2e5308f484bcf6d242e70cd69ed89f7b5b11192b28bd4f1e750f999befa91c009b7e9d9f2eda930b9209ff850fcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
